name: Run tests on any Push event
# Запуск при любом push евенте в любой ветке, за исключением релизных тэгов.
# Они будт тестироваться перед сборкой
on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      # Чекаутим код
      - uses: actions/checkout@master
      # Устанавливаем python нужной версии
      - uses: actions/setup-python@v1
        with:
          python-version: '3.12.4'
          architecture: 'x64'
      - name: Install pipenv
        # Устанавливаем pipenv
        run: pip install pipenv
      - name: Install requirements
        # Устанавливаем зависимости
        run: pipenv install --dev
      - name: Run tests
        run: pipenv run pytest